<?php

use CRM_Pcadets_ExtensionUtil as E;


return array(
  'pcadets_available_dates' => array(
    'group_name' => 'Power The Cadets Settings',
    'group' => 'pcadets',
    'name' => 'pcadets_available_dates',
    'add' => '5.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('Select the option group that provides a list of dates for the current year.'),
    'title' => E::ts('Available dates'),
    'type' => 'Int',
    'quick_form_type' => 'Select',
    'html_type' => 'Select',
    'html_attributes' => array(
      'class' => 'crm-select2',
      'style' => "width:auto;",
    ),
    'X_options_callback' => 'CRM_Pcadets_Form_Settings::getAvailableDatesOrSoftCreditOptions',
  ),
  'pcadets_soft_credit_contacts' => array(
    'group_name' => 'Power The Cadets Settings',
    'group' => 'pcadets',
    'name' => 'pcadets_soft_credit_contacts',
    'add' => '5.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('Select the option group that provides a list of dates for the current year.'),
    'title' => E::ts('Soft credit contacts'),
    'type' => 'Int',
    'quick_form_type' => 'Select',
    'html_type' => 'Select',
    'html_attributes' => array(
      'class' => 'crm-select2',
      'style' => "width:auto;",
    ),
    'X_options_callback' => 'CRM_Pcadets_Form_Settings::getAvailableDatesOrSoftCreditOptions',
  ),
  'pcadets_total_meal_value_per_day' => array(
    'group_name' => 'Power The Cadets Settings',
    'group' => 'pcadets',
    'name' => 'pcadets_total_meal_value_per_day',
    'add' => '5.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('Indicating the total dollar target for meal sponsorships for one day.'),
    'title' => E::ts('Total meal value per day'),
    'type' => 'Int',
    'quick_form_type' => 'Element',
    'html_type' => 'Text',
  ),
  'pcadets_meal_sponsorship_contribution_page_id' => array(
    'group_name' => 'Power The Cadets Settings',
    'group' => 'pcadets',
    'name' => 'pcadets_meal_sponsorship_contribution_page_id',
    'add' => '5.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('Select an existing contribution page to be used for meal sponsorships.'),
    'title' => E::ts('Meal sponsorship contribution page'),
    'type' => 'Int',
    'quick_form_type' => 'Select',
    'html_type' => 'Select',
    'html_attributes' => array(
      'class' => 'crm-select2',
      'style' => "width:auto;",
    ),
    'X_options_callback' => 'CRM_Pcadets_Form_Settings::getMealSponsorshipContributionPageOptions',
  ),
  'pcadets_custom_field_sponsored_date' => array(
    'group_name' => 'Power The Cadets Settings',
    'group' => 'pcadets',
    'name' => 'pcadets_custom_field_sponsored_date',
    'add' => '5.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('Select the contribution-linked custom date field that stores the date being sponsored for meal sponsorships.'),
    'title' => E::ts('Custom Field: Sponsored Date'),
    'type' => 'Int',
    'quick_form_type' => 'Select',
    'html_type' => 'Select',
    'html_attributes' => array(
      'class' => 'crm-select2',
      'style' => "width:auto;",
    ),
    'X_options_callback' => 'CRM_Pcadets_Form_Settings::getMealCustomFieldsOptions',
  ),
  'pcadets_custom_field_remain_anonymous' => array(
    'group_name' => 'Power The Cadets Settings',
    'group' => 'pcadets',
    'name' => 'pcadets_custom_field_remain_anonymous',
    'add' => '5.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('Select the contribution-linked custom yes/no field that stores whether the donor wishes to remain anonymous.'),
    'title' => E::ts('Custom Field: Remain anonymous'),
    'type' => 'Int',
    'quick_form_type' => 'Select',
    'html_type' => 'Select',
    'html_attributes' => array(
      'class' => 'crm-select2',
      'style' => "width:auto;",
    ),
    'X_options_callback' => 'CRM_Pcadets_Form_Settings::getMealCustomFieldsOptions',
  ),
  'pcadets_remain_anonymous_invert' => array(
    'group_name' => 'Power The Cadets Settings',
    'group' => 'pcadets',
    'name' => 'pcadets_remain_anonymous_invert',
    'add' => '5.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'default' => 0,
    'description' => E::ts('Check this box if a "yes" answer to the "Remain anonymous" custom field should cause the sponsor\'s name to be displayed.'),
    'title' => E::ts('Remain anonymous - Invert value'),
    'type' => 'Boolean',
    'quick_form_type' => 'YesNo',
    'html_type' => 'Checkbox',
  ),
  'pcadets_custom_field_display_name' => array(
    'group_name' => 'Power The Cadets Settings',
    'group' => 'pcadets',
    'name' => 'pcadets_custom_field_display_name',
    'add' => '5.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('Select the contribution-linked custom text field that stores display name for donors who specify one.'),
    'title' => E::ts('Custom Field: Display name'),
    'type' => 'Int',
    'quick_form_type' => 'Select',
    'html_type' => 'Select',
    'html_attributes' => array(
      'class' => 'crm-select2',
      'style' => "width:auto;",
    ),
    'X_options_callback' => 'CRM_Pcadets_Form_Settings::getMealCustomFieldsOptions',
  ),
  'pcadets_custom_field_message' => array(
    'group_name' => 'Power The Cadets Settings',
    'group' => 'pcadets',
    'name' => 'pcadets_custom_field_message',
    'add' => '5.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('Select the contribution-linked custom text field that stores the "Message" value which a donor may provide.'),
    'title' => E::ts('Custom Field: Message'),
    'type' => 'Int',
    'quick_form_type' => 'Select',
    'html_type' => 'Select',
    'html_attributes' => array(
      'class' => 'crm-select2',
      'style' => "width:auto;",
    ),
    'X_options_callback' => 'CRM_Pcadets_Form_Settings::getMealCustomFieldsOptions',
  ),
  'pcadets_maximum_donors_to_show' => array(
    'group_name' => 'Power The Cadets Settings',
    'group' => 'pcadets',
    'name' => 'pcadets_maximum_donors_to_show',
    'add' => '5.0',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('Integer indicating the maximum number of donor names to reveal for each date upon loading the Listings Page. For dates having more donors than this number, donor names will be hidden behind a "View more" button.'),
    'title' => E::ts('Maximum donors to reveal on Listings Page'),
    'type' => 'Int',
    'quick_form_type' => 'Element',
    'html_type' => 'Text',
  ),
);
